### ISSUE TITLE
integration with coverty

### ISSUE THREAD

**Issue by kbilsted** [kbilsted/StatePrinter#16]
For the build server

**Comment by mathieubrun** [comment]
Hi @kbilsted 

I've already done for my project here : https://github.com/mathieubrun/SampleDataGenerator/blob/master/appveyor.yml

As you can see, appveyor file is a bit more verbose. If you want I'll adapt and put in a PR.

Mathieu

**Comment by kbilsted** [comment]
Hi great 

Never got around to even running it locally.. not sure why right now :) does it produce issues worth fixing?

**Comment by mathieubrun** [comment]
Depends on the codebase I think. For me it detected 2 null dereferences in my unit tests.

Running it locally is straightforward : cov-build --dir cov-int msbuild /t:Rebuild
