### ISSUE TITLE
Does stateprinter use the ToString() method of an object if it was explicity implemented?

### ISSUE THREAD

**Issue by sjdirect** [kbilsted/StatePrinter#3]
I'm manually checking this first but didn't know if your lib handles that internally. Great lib thanks a lot!

**Comment by sjdirect** [comment]
Specifically i'm running this check before calling your PrintObject() method...

        private bool HasExplicitToStringImpl(object obj)
        {
            var objType = obj.GetType();
            return objType.GetMethod("ToString").DeclaringType == objType;
        }

**Comment by kbilsted** [comment]
No, the library is split into separate phases. One harvest information, the other handles how the collected data is being presented.

**Comment by sjdirect** [comment]
Thanks for the quick resonse and the great library. I'll close the issue.

**Comment by kbilsted** [comment]
We could have a method like


Dictionary<Type, bool> cache = new dict..

public string PrintOrUseExistingToString(object objectToPrint)
{
        var objType = obj.GetType();
        bool hasToString;
        if(!cache.TryGet(objType, out hasToString))
        {
           hasToString = objType.GetMethod("ToString").DeclaringType == objType;
           cache[objType] = hasToString;
         }

         return hasToString ? objectToPrint.ToString() : PrintObject(objectToPrint);
}


}

**Comment by kbilsted** [comment]
What is it you are trying to achieve?

**Comment by sjdirect** [comment]
That method would serve me well and only detecting tostring on the lowest level object works ok for me. 

I'm working on an AOP Aspect using Postsharp that logs information about the method calls. I want to include the method's arguments in the log message as well. This is a general purpose library so I dont want to ignore a ToString() just in case someone would rather provide a better representation of the data they want to see in the logs instead me just printing all the properties of the object. 

Either way, if you think it would be beneficial to others, adding the method you purposed would be cool.

Thanks!

**Comment by kbilsted** [comment]
The solution sketched above will only be the entry point of the object graph. I am thinking what we want instead is a fieldharvester that is ToString() aware, but it requires changes to the internals. A change I have planned anyway due to some fancy extension planned for the future. 

Such a solution will not require orthogonal configuration and it will work on all objects of the graph.

**Comment by sjdirect** [comment]
Cool, i look forward to it.

Thanks

**Comment by kbilsted** [comment]
Have a look at https://github.com/kbilsted/StatePrinter/blob/master/StatePrinter.Tests/FieldHarvesters/ToStringAwareHarvester.cs 

what are your reactions?

**Comment by sjdirect** [comment]
At a quick glance it looks like that will work. I'll plug this in within
the next few days to see for sure.

Thanks!
Steven

**Comment by sjdirect** [comment]
Hi,

Could you please create a nuget package for this? It's hard for me to work
from source since i'm using it in two separate products.

Thanks
Steven

**Comment by kbilsted** [comment]
I was planning a release soon, but wanted your thoughts first. I've extended the test https://github.com/kbilsted/StatePrinter/blob/master/StatePrinter.Tests/FieldHarvesters/ToStringAwareHarvesterTest.cs slightly yesterday

Alternatively you can run the script inside the project that creates a nuget yourself.

**Comment by sjdirect** [comment]
Hi, quick question. How do i get stack the harvestors? I need to do something like this...

            var cfg = ConfigurationHelper.GetStandardConfiguration("");
            cfg.Add(new PublicFieldsHarvester());
            cfg.Add(new ToStringAwareHarvester());

            cfg.OutputFormatter = new JsonStyle(cfg.IndentIncrement);
            StatePrinter = new Stateprinter(cfg);;

I want to only print public fields but also want to leverage the ToStringAware functionality. Also I will likely have a pull request for you regarding an issue i encountered.

Thanks

**Comment by kbilsted** [comment]
I'm not sure what you want to do with adding both harvesters. I would probably write my own harvester given its so succint to do. Your bespoke implementation can implement CanHandleType() if you need the behaviour on only a subset of the types to harvest. 

Pullrequests are welcome
