### ISSUE TITLE
Field harvester factory method

### ISSUE THREAD

**Issue by kbilsted** [kbilsted/StatePrinter#33]
We need an easy way to create an anonymous field harvester. The configuration should have an AddHarvester taking two lambdas as argument which should create an instance of a new AnonymousFieldHarveater

**Comment by harrybellamy** [comment]
Having been in the configuration code recently I think this can be closed (`Configuration.AddHandler` satisfies this requirement).

**Comment by kbilsted** [comment]
Fixed in #48
