### ISSUE TITLE
Ambigous constructors prevent StatePrinter from being used by VB.Net

### ISSUE THREAD

**Issue by eagunn** [kbilsted/StatePrinter#46]
StatePrinter has two constructors: Stateprinter and StatePrinter (deprecated)

Believe it or not (took me a while), when viewed from VB.Net, these are ambiguous because VB is case insensitive.

AFAICS, this completely prevents SP from being used from VB without the developer writing her own C# wrapper class to hide the original SP constructors.

Please see my question at StackOverflow which gives a bit more detail: http://stackoverflow.com/questions/35092412/using-stateprinter-from-vb-rather-than-c-sharp-to-implement-tostring

The simplest solution would be to drop the old constructor altogether and beware case-only differences in the future. If you can't do that for backward compatibility reasons, perhaps you could cut a VB-only, futures-only version.

**Comment by kbilsted** [comment]
Hi @eagunn 

VB is definitely not a language I had in mind when I created Stateprinter. :-)

That being said, I think your bug report shows there is a need for a new name. Yet again. I think we can provide a different class with that does not have the casing issue. I think this can be implemented the same way the existing has been implemented. I can create a new release in the week to come if you want to test a pre-release for me? :)

**Comment by eagunn** [comment]
Kasper,

Thank you very much for getting back to me. VB has been an adventure for me
these last few months but I can, now, understand some of the reasons why it
refuses to go away.

I would be happy to test a new version. I'm actively working on vb code
with complex structures and some way to log their content would be
incredibly useful.

Timing is the only issue.

I am on deadline to produce production quality code early next week and
then I am on vacation the week of 15 Feb.

The first time I'd be available to try your pre-release code would be the
week of 22 Feb.

ag

On Wed, Feb 3, 2016 at 1:16 PM, Kasper B. Graversen <
notifications@github.com> wrote:

> Hi @eagunn <https://github.com/eagunn>
>
> VB is definitely not a language I had in mind when I created Stateprinter.
> :-)
>
> That being said, I think your bug report shows there is a need for a new
> name. Yet again. I think we can provide a different class with that does
> not have the casing issue. I think this can be implemented the same way the
> existing has been implemented. I can create a new release in the week to
> come if you want to test a pre-release for me? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbilsted/StatePrinter/issues/46#issuecomment-179438418>
> .
>



-- 
Anne Gunn, Founder
Sheridan Programmers Guild
307 461 9616

**Comment by kbilsted** [comment]
@eagunn  sorry I have been swamped at work. Will resume this shortly.

@romkatv  perhaps you have a suggestion for the naming of the assembly and top-level namespace?

**Comment by kbilsted** [comment]
fixed
