### ISSUE TITLE
Problem with rewriting expected values if value contains brackets.

### ISSUE THREAD

**Issue by addamichal** [kbilsted/StatePrinter#50]
Current version does not correctly rewrite expected  value, if given value contains brackets.
Example:

```var actual = new List<int>() { 1, 2, 3 };
string expected = @"new List<Int32>()
{
    [0] = 1
    [1] = 2
    [2] = 3
    [3] = 4
}";
TestHelper.Assert().PrintEquals(expected, actual);
```

I created a pull request with proposed fix: [https://github.com/kbilsted/StatePrinter/pull/49](https://github.com/kbilsted/StatePrinter/pull/49)

**Comment by kbilsted** [comment]
There are similar bugs for other regex meta characters such as { and * ..

We could fix them all now... if it is ever likely such an output is ever used. I guess your PR arose from a problematic situation?

Also perhaps then all the calls to replace should be reimplemented to gain speed

**Comment by kbilsted** [comment]
merged PR
