### ISSUE TITLE
proposal: Change minimum .net supported version

### ISSUE THREAD

**Issue by SimonCropp** [kbilsted/StatePrinter#53]
So the current min is .net 3.5. which was released ~11 years ago.

Perhaps the new min could be 4.5.2, released ~4 years ago ?

I know this is a breaking change, but people still using 3.5 can stay on the old nuget until they can move on to  4.5.2.

related to: https://github.com/kbilsted/StatePrinter/issues/52

**Comment by kbilsted** [comment]
Sure de could. What advantages will we get ?

**Comment by SimonCropp** [comment]
I was looking at adding netstandard support to stateprinter. Which means using the new sdk csproj format with targetframworks, so u can multi target

Unfortunately net35 and lower can be problematic depending on machine setup https://github.com/Microsoft/msbuild/issues/1333

Aslo net35 is an obstacle for contributers as a decreasing number of devs have the 35 sdk installed

**Comment by kbilsted** [comment]
.net standard could be fun. Haven't looked into whether it can be mapped at all. E.g. what introspective capabilities .net standard has. Or how we can read external environment settings. Perhaps we can look into these matters first.

So far no one has said they couldn't contribute due to the 3.5 restriction.

**Comment by SimonCropp** [comment]
so is that a "yes we can move to min of 4.5.2"? :)

**Comment by kbilsted** [comment]
I may be slow but I still don't understand  how going to 4.5.2 brings us closer to core:)

**Comment by SimonCropp** [comment]
i no longer need this. so will close for now
